### ISSUE TITLE
Installation problems -  ValueError: Entry points must be listed in groups

### ISSUE THREAD

**Issue by Mr-Blonde** [tjltjl/plycutter#19]
I am having trouble installing plycutter. I tried various methods and OS to install plycutter but with no success. First I tried pipx on MacOS (11.2 - x86) which resulted in:

```
Traceback (most recent call last):
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 391, in run
    installed = install_given_reqs(
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 80, in install_given_reqs
    requirement.install(
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 788, in install
    install_wheel(
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 819, in install_wheel
    _install_wheel(
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 635, in _install_wheel
    console, gui = get_entrypoints(distribution)
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 134, in get_entrypoints
    console = distribution.get_entry_map('console_scripts')
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2859, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "/Users/mr-blonde/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2531, in parse_map
    raise ValueError("Entry points must be listed in groups")
ValueError: Entry points must be listed in groups
Cannot determine package name from spec 'git+https://github.com/tjltjl/plycutter.git'. Check package spec for errors.
```

Then I started a VM with Ubuntu 20.4 and tried pipx again:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ccu0azxi/setup.py", line 8, in <module>
        setup()
      File "/home/mr-blonde/.local/pipx/venvs/plycutter/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/mr-blonde/.local/pipx/venvs/plycutter/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 601, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/mr-blonde/.local/pipx/venvs/plycutter/lib/python3.8/site-packages/setuptools/command/install_scripts.py", line 48, in run
        for args in writer.get_args(dist, cmd.as_header()):
      File "/home/mr-blonde/.local/pipx/venvs/plycutter/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 2167, in get_args
        for name, ep in dist.get_entry_map(group).items():
      File "/home/mr-blonde/.local/pipx/venvs/plycutter/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "/home/mr-blonde/.local/pipx/venvs/plycutter/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2531, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mr-blonde/.local/pipx/venvs/plycutter/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ccu0azxi/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ccu0azxi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jauv6pll/install-record.txt --single-version-externally-managed --compile --install-headers /home/mr-blonde/.local/pipx/venvs/plycutter/include/site/python3.8/plycutter Check the logs for full command output.
'/home/mr-blonde/.local/pipx/venvs/plycutter/bin/python -m pip install master.zip -q' failed
```

Finally I tried to install plycutter manually by installing all dependencies and then running `python3 setup.py install` (Ubuntu 20.4). That again resulted in the "ValueError: Entry points must be listed in groups" issue.

I am not very familiar with python and its environments. I know that sometimes something can be completely off with dependencies and so on. I am a bit puzzled, however, that it happens in three different environments (pipx on MacOS, pipx on Ubuntu and native python3 env on Ubuntu).

Can you help me out here?

**Comment by traverseda** [comment]
Looks like the `setup.cfg` isn't quite working right. You can go back a few commits and it will work, use this command

`pipx install git+https://github.com/tjltjl/plycutter.git@8bbfcd0576317c472a0d090bbc08f6ed8ecfa2df`.

**Comment by Mr-Blonde** [comment]
> Looks like the `setup.cfg` isn't quite working right. You can go back a few commits and it will work, use this command
> 
> `pipx install git+https://github.com/tjltjl/plycutter.git@8bbfcd0576317c472a0d090bbc08f6ed8ecfa2df`.

That worked. Thank you!

**Comment by tjltjl** [comment]
I've reproduced this and am working on it

**Comment by tjltjl** [comment]
Pushed a change to master that seems to fix it; but you need to run "python setup.py clean" before it works and If you can't run that you need to manually remove the egg-info.

I have much less faith in the python packaging frameworks than an hour ago...

**Comment by tjltjl** [comment]
Please let me know whether this works, and thanks for reporting it and @traverseda for following up on it

**Comment by traverseda** [comment]
Seems to work for me, no need to run `setup.py clean`, just a standard `pipx install git+https://github.com/tjltjl/plycutter.git`.

**Comment by tjltjl** [comment]
Cool, thanks!
