### ISSUE TITLE
Spawning from Inkscape fails | new extension

### ISSUE THREAD

**Issue by vmario89** [tjltjl/plycutter#23]
Hi!
i found PlyCutter just today and wanted to integrate it as extension into Inkscape. I made some frontend and dxf-to-svg wrapper. Unfortunately i cant get it to work because some import errors occurs which i dont know how to fix.
You can get the files for Inkscape 1.1+ here: https://github.com/vmario89/mightyscape-1.X-zipmirror/blob/0b1ad91892ee523dcfe6d5e835c2df0302da9cf5/plycutter.zip

the error:
```
plycutter --thickness 6.0 --min_finger_width 3.0 --max_finger_width 5.0 --support_radius 12.0 --final_dilation 0.05000000074505806 --random_seed 42 -o "/tmp/PlyTest0.1.dxf" "/home/tomate/Downloads/asd/tests/data/PlyTest0.1.stl"
PlyCutter failed: 1 b'' b'INFO:plycutter.command_line:Loading "/home/tomate/Downloads/asd/tests/data/PlyTest0.1.stl. Will write "/tmp/PlyTest0.1.dxf""
WARNING:trimesh:Data not utf-8! Trying ISO-8859-1 (confidence 0.73)
INFO:plycutter.command_line:Parameters: Namespace(thickness=mpq(6,1), min_finger_width=mpq(3,1), max_finger_width=mpq(5,1), support_radius=mpq(12,1), debug=False, vdebug=False, final_dilation=mpq(2500000037252903,50000000000000000), random_seed=42, only_sheets=None, output_file=\'/tmp/PlyTest0.1.dxf\', infile=\'/home/tomate/Downloads/asd/tests/data/PlyTest0.1.stl\')
INFO:plycutter.command_line:Creating sheetplex
DEBUG:plycutter.create_sheetplex:Facet 5: [-0.99619472  0.08715574  0.        ] 5.892729859624524e-09
Traceback (most recent call last):
  File "/usr/local/bin/plycutter", line 33, in <module>
    sys.exit(load_entry_point(\'plycutter==0.0\', \'console_scripts\', \'plycutter\')())
  File "/usr/local/lib/python3.9/site-packages/plycutter-0.0-py3.9.egg/plycutter/command_line.py", line 89, in main
  File "/usr/local/lib/python3.9/site-packages/plycutter-0.0-py3.9.egg/plycutter/create_sheetplex.py", line 51, in create_sheetplex
  File "/usr/local/lib/python3.9/site-packages/plycutter-0.0-py3.9.egg/plycutter/create_sheetplex.py", line 111, in create_sheets
  File "/usr/local/lib/python3.9/site-packages/plycutter-0.0-py3.9.egg/plycutter/create_sheetplex.py", line 112, in <listcomp>
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/caching.py", line 109, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/path/path.py", line 1183, in polygons_full
    full = [None] * len(self.root)
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/caching.py", line 109, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/path/path.py", line 1510, in root
    populate = self.enclosure_directed  # NOQA
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/caching.py", line 109, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/path/path.py", line 1538, in enclosure_directed
    root, enclosure = polygons.enclosure_tree(self.polygons_closed)
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/path/polygons.py", line 56, in enclosure_tree
    tree = Rtree()
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/exceptions.py", line 48, in failed
    raise exc
  File "/usr/local/lib/python3.9/site-packages/trimesh-3.9.34-py3.9.egg/trimesh/path/polygons.py", line 27, in <module>
    from rtree import Rtree
ImportError: cannot import name \'Rtree\' from \'rtree\' (/usr/share/inkscape/extensions/rtree.py)
```
looks like duplicated Rtree import but i dont understand why Inkscape's python process collides with this spawning.

**Comment by vmario89** [comment]
finally found the issue in environment variables. thanks for your hint. that helped

my workaround was to exlude the extensions dir from inkscape in the subprocess call. 

 ```
       #create a new env for subprocess which does not contain extensions dir because there's a collision with "rtree.py"
        pypath = ''
        for d in sys.path:
            if d != '/usr/share/inkscape/extensions':
                pypath = pypath + d + ';'
        neutral_env = os.environ.copy()
        neutral_env['PYTHONPATH'] = pypath

        p = Popen(plycutter_cmd, shell=True, stdout=PIPE, stderr=PIPE, env=neutral_env)
```
